// One-off extraction of the v0 icon set into plain path data.
//
// v0 stored icons as React <path> ELEMENTS, so they could not be shared with
// Vue/Svelte/Angular. Every presentation attribute was identical across all of
// them (fill="none", strokeWidth=2, round caps/joins), so those move to CSS and
// what remains is pure data: name -> the `d` strings.
//
// Run: node packages/core/scripts/extract-icons.mjs
// The output is committed; this script exists to document provenance and to
// make a re-run auditable. HAND-REVIEW the diff — a typo in a `d` string is
// invisible until someone renders that icon.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(here, "../../../legacy/v0/src/components/base/Icon/Icon.tsx");
const OUT = join(here, "../src/icons.ts");

const src = readFileSync(SOURCE, "utf8");

// Isolate the `const icons = { ... };` object literal.
const start = src.indexOf("const icons = {");
if (start === -1) throw new Error("could not find the icons object");
let depth = 0;
let end = -1;
for (let i = src.indexOf("{", start); i < src.length; i++) {
  if (src[i] === "{") depth++;
  else if (src[i] === "}") {
    depth--;
    if (depth === 0) {
      end = i;
      break;
    }
  }
}
const body = src.slice(src.indexOf("{", start) + 1, end);

// Split into top-level `name: (...)` entries. Keys sit at the start of a line
// with exactly two spaces of indentation in the source.
const entries = [];
const keyRe = /^ {2}([A-Za-z][A-Za-z0-9]*):/gm;
const keys = [...body.matchAll(keyRe)];
for (let i = 0; i < keys.length; i++) {
  const from = keys[i].index + keys[i][0].length;
  const to = i + 1 < keys.length ? keys[i + 1].index : body.length;
  const name = keys[i][1];
  const chunk = body.slice(from, to);
  const ds = [...chunk.matchAll(/\sd="([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) {
    console.warn(`!! ${name}: no path data found — inspect manually`);
    continue;
  }
  entries.push([name, ds]);
}

const multi = entries.filter(([, ds]) => ds.length > 1);
const names = entries.map(([n]) => n);

const out = `// GENERATED by scripts/extract-icons.mjs from the v0 Icon component.
// Hand-reviewed. Do not edit casually — regenerate or edit deliberately.
//
// Icons are DATA, not components, so all four framework adapters render the
// identical <svg><path d="..." /></svg> from this one source. Every presentation
// attribute (fill, stroke-width, linecap, linejoin) lives in @crosskit-ui/styles
// instead, which is why the markup is byte-identical across frameworks and why
// there is no strokeLinecap-vs-stroke-linecap casing problem to solve.

export const ICON_VIEW_BOX = "0 0 24 24";

/** ${entries.length} icons; ${multi.length} of them multi-path. */
export const iconPaths = {
${entries.map(([name, ds]) => `  ${name}: [${ds.map(d => JSON.stringify(d)).join(", ")}],`).join("\n")}
} as const satisfies Record<string, readonly string[]>;

export type IconName = keyof typeof iconPaths;

export const ICON_NAMES = Object.keys(iconPaths) as IconName[];

export function getIconPaths(name: IconName): readonly string[] | undefined {
  return iconPaths[name];
}

export const isIconName = (value: string): value is IconName => value in iconPaths;
`;

writeFileSync(OUT, out);

console.log(`extracted ${entries.length} icons (${multi.length} multi-path) -> src/icons.ts`);
if (multi.length)
  console.log("multi-path:", multi.map(([n, ds]) => `${n}(${ds.length})`).join(", "));
console.log("first/last:", names[0], "...", names[names.length - 1]);
