name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      message:
        description: 'Commit message'
        required: true
        default: 'chore: new release'
      should_release:
        description: 'Whether to bump version and create a GitHub release'
        required: true
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Bump version and publish
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version }} -m "chore(release): bump version to %s"
          npm publish --access public
          echo "new_version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        if: ${{ github.event.inputs.should_release }}
        run: git push --follow-tags

      - name: Create GitHub Release
        if: ${{ github.event.inputs.should_release }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          release_name: Release v${{ steps.bump_version.outputs.new_version }}
          draft: false
          prerelease: false
